version: '3'

services:
  config-server:
    build: ./config-server
  eureka-server:
    build: ./eureka-server
  zuul-server:
    build: ./zuul-server
    ports:
      - "8765:8765"
  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  users-service:
    build: ./users-service
  boards-service:
    build: ./boards-service
  quivers-service:
    build: ./quivers-service
